### ISSUE TITLE
Space around multiply (`*`) operator is not honored

### ISSUE THREAD

**Issue by luislavena** [asterite/rufo#46]
Hello!

Given the following sample:

```ruby
a = " "*(10+5)
```
And here is the output:

```ruby
a = " "*(10 + 5)
```

I expected space will be added between all the operators, not only `+` but `*` too, of course, the only exception should be exponent, as described in the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#spaces-operators).

Details:

- `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`
- rufo (master@b3d8436)

Thank you! :heart: :heart: :heart:

**Comment by asterite** [comment]
Ah, this is something I chose to do in a different way than the Ruby style guide. I chose to do what `gofmt` does: if there's a space, keep it (and add a space to the right). If not, don't write one. But only for `*`, `/` and `**`.

The reason behind this is that if I write this:

```ruby
2*x + 3*y + z
```

I'd really like that to be kept like that. It makes sense to write it like that because `*` has a stronger association, and probably you'd write that in math too. Otherwise it will always be formatted like this:

```ruby
2 * x + 3 * y + z
```

and now it's just a bit harder to understand.

In any case, if you do add a space before the `*` it will keep it. So ultimately this is a programmer's choice.

However, I can add a setting to always surround operators with spaces. What do you think?

**Comment by luislavena** [comment]
I personally think that more settings will end Rufo being rubocop 😁

I'm fine with the default, maybe is worth noticing this preference over the default Ruby style guide to avoid others asking the same question.

Thank you for the fast response! ❤❤❤

**Comment by asterite** [comment]
Indeed, I'd like to keep Rufo simple and with very few configurations :-)

I marked this with the `docs` label, I'll later add this to the README. I also plan to write a lot more there, now that the tool is pretty much done.
