### ISSUE TITLE
Whitespace when indenting else in case statement

### ISSUE THREAD

**Issue by jgrau** [asterite/rufo#96]
<img width="1069" alt="screen shot 2017-07-05 at 14 59 14" src="https://user-images.githubusercontent.com/108088/27865403-b93f16f0-6192-11e7-8099-a56fc1b5ceb2.png">

When the statement is on the same line as the `else` statement it works but when it's on the next line then whitespace is added to the line containing the `else`

**Comment by jgrau** [comment]
Hmm. Not sure I agree with the behaviour when it's on the same line either

```
        case pricing_scheme
        when :per_meeting           then price
        when :per_person, :per_unit then price * quantity
        when :per_hour              then price * duration_in_hours
        when :per_person_per_hour   then price * quantity * duration_in_hours
        else                             fail ArgumentError, "Pricing scheme #{pricing_scheme} is not supported"
        end
```

**Comment by jgrau** [comment]
At least if the line is too long it should probably be newlined.

**Comment by asterite** [comment]
Indeed, that extra whitespace shouldn't be there.

About the last snippet: you can remove the whitespace by setting `spaces_around_when` to `:one` (this is also applied to `else` there, I should probably update the README).

Rufo does not insert newlines to fit a specified column width, and will probably never will (I never found it useful because these days screens are very big, and if you need to read that string you just scroll a bit, but usually you don't need to know the exact contents)
